[project]
name = "opticas-medidas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=1.24.0",
    "pandas>=1.5.0",
    "matplotlib>=3.6.0",
    "scipy>=1.10.0"
]
